name: Run Checks on PR Comment
on:
  issue_comment:
    types: [created]
permissions: write-all
jobs:
  check:
    if: contains(github.event.comment.html_url, '/pull/')
    runs-on: [ubuntu-latest]
    steps:
      - name: Run Checks
        if: contains(github.event.comment.body, '/test') 
        run: |
          # Trigger all checks on the PR
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/quarkiverse/quarkus-openapi-generator/check-runs" \
            -d '{
              "name": "Java CI with Maven"
              "head_sha": "${{ github.event.issue.pull_request.head.sha }}"
            }'
