name: Run Checks on PR Comment
on:
  issue_comment:
    types: [created]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for test command
        id: check_command
        uses: actions/github-script@v5
        with:
          script: |
            const command = '/test';
            const comment = context.payload.comment.body;
            if (comment.includes(command)) {
              console.log('::set-output name=run_checks::true');
            } else {
              console.log('::set-output name=run_checks::false');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Checks
        if: steps.check_command.outputs.run_checks == 'true'
        run: |
          # Trigger all checks on the PR
          curl -X POST \
            -H "Accept: application/vnd.github.antiope-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/check-runs" \
            -d '{
              "head_sha": "${{ github.event.issue.pull_request.head.sha }}"
            }'
